name: Deploy to Firebase

on:
  push:
    branches:
      - main
env:
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm i

    - name: Build the React app
      run: CI=false npm run build

    - name: Install Firebase CLI
      run: npm install -g firebase-tools
      
    - name: Login to Firebase
      run: firebase login:ci --interactive --token ${{ env.FIREBASE_TOKEN }}

    - name: Deploy the app
      run: firebase deploy --only hosting 

